# Generated by Django 2.1.2 on 2018-10-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_pessoa_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Cliente',
        ),
    ]
